config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # use our own passwords controller
  devise_for :users, controllers: { passwords: "passwords" }

  resources :account_requests, only: %i[show new create]

  # We use high voltage to manage static content incl home page
  # See -- config/initializers/high_voltage.rb
  # for the home/root page
  #  get "/pages/*id" => 'high_voltage/pages#show', as: :page, format: false
  get "/password/reset" => "reset_password#reset", as: :after_password_reset

  mount PafsCore::Engine, at: "/pc"

  resource :cookies, only: %i[edit update] do
    member do
      post :accept_analytics
      post :reject_analytics
      post :hide_this_message
    end
  end

  get "/cookies", to: "pages#cookies"

  match "(errors)/:status", to: PafsCore::Engine, via: :all, constraints: { status: /\d{3}/ }

  root to: "pafs_core/projects#index"

end

app/models/user.rb
# Play nice with Ruby 3 (and rubocop)
# frozen_string_literal: true

class User < PafsCore::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, # :registerable, :rememberable
         :recoverable, :trackable, :timeoutable, # :validatable,
         :password_archivable, :session_limitable, :secure_validatable

  def active_for_authentication?
    !disabled?
  end

  def inactive_message
    "You must register for an account before using this service" if disabled?
  end
end

app/controllers/account_requests_controller.rb
# frozen_string_literal: true

class AccountRequestsController < ApplicationController
  def show
    @account_request = PafsCore::AccountRequest.find_by!(slug: params[:id])
  end

  def new
    @account_request = PafsCore::AccountRequest.new
  end

  def create
    @account_request = PafsCore::AccountRequest.new(account_params)
    if @account_request.save
      send_emails
      redirect_to @account_request
    else
      render "new"
    end
  end

  private

  def account_params
    params.require(:account_request)
          .permit(:first_name, :last_name, :email, :organisation, :job_title,
                  :telephone_number, :terms_accepted, :provisioned)
  end

  def full_name
    "#{@account_request.first_name} #{@account_request.last_name}"
  end

  def send_emails
    AccountRequestMailer.new_account_request(@account_request).deliver_later
    AccountRequestMailer.confirmation_email(@account_request).deliver_later
  end
end

app/controllers/application_controller.rb
# Play nice with Ruby 3 (and rubocop)
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include PafsCore::CustomHeaders

  helper PafsCore::Engine.helpers

  # This is a nested template that ultimately calls the gov uk template layout
  # This allows us to auto insert code into any of the hooks provided by the GDS layout.
  layout ->(_) { "pafs" }
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :cache_busting

  default_form_builder GOVUKDesignSystemFormBuilder::FormBuilder

  private

  def custom_headers
    response_headers!(response)
  end

end

app/controllers/cookies_controller.rb
# frozen_string_literal: true

class CookiesController < ApplicationController
  def accept_analytics
    write_cookie(:cookies_policy, :analytics_accepted)
    redirect_back fallback_location: "/"
  end

  def reject_analytics
    write_cookie(:cookies_policy, :analytics_rejected)
    redirect_back fallback_location: "/"
  end

  def hide_this_message
    write_cookie(:cookies_preferences_set, true)
    redirect_back fallback_location: "/"
  end

  def update
    # Google writes the cookies as ".hostname"
    # so we need to state the domain when removing
    cookies.to_hash.each_pair do |k, _v|
      cookies.delete k, domain: ".#{request.hostname}"
    end

    if params[:analytics] == "accept"
      write_cookie(:cookies_policy, :analytics_accepted)
    else
      write_cookie(:cookies_policy, :analytics_rejected)
    end
    write_cookie(:cookies_preferences_set, true)

    redirect_to edit_cookies_path(cookies_updated: true)
  end

  protected

  def write_cookie(name, value)
    cookies[name] =
      {
        value: value,
        expires: 1.year
      }
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  layout "pafs"
end

app/controllers/passwords_controller.rb
# frozen_string_literal: true

class PasswordsController < Devise::PasswordsController
  # POST override the create method to prevent giving clues
  # to whether the email address exists / is registered
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    # whether successful or not we carry on
    # so we don't give away whether the email is registered or not
    if resource_params.fetch(:email, nil).present?
      flash[:email] = resource_params.fetch(:email)
      redirect_to after_password_reset_path
    else
      # they haven't provided an email address so prompt them for it
      respond_with(resource)
    end
  end
end

app/controllers/reset_password_controller.rb
# frozen_string_literal: true

class ResetPasswordController < ApplicationController
  def reset
    redirect_to pafs_core.projects_path if flash[:email].blank?
  end
end

app/helpers/application_helper.rb
# Play nice with Ruby 3 (and rubocop)
# frozen_string_literal: true

module ApplicationHelper
  def revision_hash
    Rails.application.config.x.revision
  end

  def not_policy_page?(supplied_path)
    supplied_path != Rails.application.routes.url_helpers.cookies_path &&
      supplied_path != main_app.page_path("privacy_notice")
  end

  def migrate_devise_errors_for(resource)
    # move flash messages and resource.errors to :base
    resource.errors.add(:base, flash[:alert]) if flash[:alert].present?

    if resource.errors[:password].present?
      resource.errors.full_messages_for(:password).each { |m| resource.errors.add(:base, m) }
    elsif resource.errors[:password_confirmation].present?
      # only add :password_confirmation errors if there are no :password errors
      resource.errors.full_messages_for(:password_confirmation).each { |m| resource.errors.add(:base, m) }
    end
    resource.errors.delete(:password)
    resource.errors.delete(:password_confirmation)
  end

  def show_return_to_overview?
    ((controller_name == "projects" && action_name != "index" && action_name != "show") ||
      (controller_name == "downloads" && action_name == "index")) &&
      !@project.nil?
  end
end

app/views/account_requests/new.html.erb
<% content_for :title, "Account request" %>
<div class="govuk-grid-row govuk-body">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l"><%= t(".heading") %></h1>
    <p><%= t(".description") %></p>
    <%= pafs_form_for @account_request do |f| %>
      <div class="form-group">
        <%= f.govuk_text_field :first_name, width: 'one-half', label: { text: t(".first_name") } %>
        <%= f.govuk_text_field :last_name, width: 'one-half', label: { text: t(".last_name") } %>
        <%= f.govuk_text_field :email, width: 'one-half', label: { text: t(".email") } %>
        <%= f.govuk_phone_field :telephone_number, width: 'one-half', label: { text: t(".telephone_number") } %>
        <%= f.govuk_text_field :organisation, width: 'one-half', label: { text: t(".organisation") } %>
        <%= f.govuk_text_field :job_title, width: 'one-half', label: { text: t(".job_title") } %>

        <p class="govuk-heading-l">Privacy Policy</p>
        <p>
          Details of our Personal Information Charter can be found at <a href="https://www.gov.uk/government/organisations/environment-agency/about/personal-information-charter">https://www.gov.uk/government/organisations/environment-agency/about/personal-information-charter</a>
        </p>
        <div>
          <div>
            <details class="govuk-details" data-module="govuk-details__text">
              <summary class="govuk-details__summary" aria-controls="show_data_collected_and_how">
                <span class="govuk-details__summary-text">
                  What of my data is being collected and how is it used?
                  What is the legal basis for the processing?
                </span>
              </summary>
              <div id="show_data_collected_and_how" class="govuk-details__text">
                <p>Personal data is collected to:</p>
                <ul class="list list-bullet">
                  <li>Verify that you are eligible for an account</li>
                  <li>Ensure your account is set up with the correct access permissions</li>
                  <li>Allow us to contact you if your request is unclear</li>
                  <li>Your contact details will be used to manage your proposal, including contacting you with queries and updates</li>
                </ul>
                <p>
                  Processing is necessary for the performance of a task carried out in the public interest or in the 
                  exercise of official authority vested in the data controller to enable Risk Management Authorities 
                  to bid for central government Grant-in-Aid funding.
                </p>
              </div>
            </details>
            <details class="govuk-details" data-module="govuk-details__text">
              <summary class="govuk-details__summary" role="button" aria-controls="show_how_will_data_be_shared">
                <span class="govuk-details__summary-text">
                  Who will my data be shared with?
                </span>
              </summary>
              <div id="how_will_data_be_shared" class="govuk-details__text">
                <p>
                  Your personal data will not be shared or disclosed to any other party outside the Environment Agency without your explicit consent.
                </p>
              </div>
            </details>
            <details class="govuk-details" data-module="govuk-details__text">
              <summary class="govuk-details__summary" role="button" aria-controls="show_data_transferred_outside_of_eea">
                <span class="govuk-details__summary-text">
                  Will my data be transferred outside of the EEA? If it will, how will it be protected?
                </span>
              </summary>
              <div id="data_transferred_outside_of_eeahow_will_data_be_shared" class="govuk-details__text">
                <p>
                  The data you provide will not be transferred outside the European Economic Area.
                </p>
              </div>
            </details>
            <details class="govuk-details" data-module="govuk-details__text">
              <summary class="govuk-details__summary" role="button" aria-controls="show_how_long_data_will_be_held">
                <span class="govuk-details__summary-text">
                  How long will my data be held for?
                </span>
              </summary>
              <div id="show_how_long_data_will_be_held" class="govuk-details__text">
                <p>
                  Your personal data will be kept by us for as long as you require access to the service
                </p>
              </div>
            </details>
            <details class="govuk-details" data-module="govuk-details__text">
              <summary class="govuk-details__summary" role="button" aria-controls="show_will_data_be_used_for_automated_decision_or_profiling">
                <span class="govuk-details__summary-text">
                  Will my data be used for automated decision-making or profiling?
                </span>
              </summary>
              <div id="show_will_data_be_used_for_automated_decision_or_profiling" class="govuk-details__text">
                <p>
                  The information you provide is not connected with individual decision making 
                  (making a decision solely by automated means without any human involvement) or profiling 
                  (automated processing of personal data to evaluate certain things about an individual).
                </p>
              </div>
            </details>
          </div>
        </div>
      </div>

      <%= f.govuk_submit t(".submit_label") %>
    <% end %>
  </div>
</div>

app/views/account_requests/show.html.erb
<% content_for :title, "Account request confirmation" %>
<div class="govuk-grid-row grid-body">
  <div class="govuk-grid-column-two-thirds">
    <div class="confirmation-box">
      <h1><%= t(".heading") %></h1>
      <p><%= t(".email_sent_to") %><br/>
        <strong class="heading-medium"><%= @account_request.email %></strong>
      </p>
    </div>
    <h2 class="heading-medium">What happens next</h2>
    <p>We will now verify this request. If successful we will contact you by email when the account has been created. This will take up to 5 working days.</p>
    <p>If you haven't heard from us within 5 working days contact us at
      <%= link_to t("global.support_email"), "mailto:#{t("global.support_email").delete(" ") }" %>
      </p>

    <%= link_to t("global.return_to_start"), main_app.root_path, class: "button", role: "button" %>
  </div>
</div>

app/views/cookies/_action_confirmed.html.erb
<div class="govuk-cookie-banner__message govuk-width-container" role="alert">
  <div class="govuk-grid-row grid-body">
    <div class="govuk-grid-column-two-thirds">
      <div class="govuk-cookie-banner__content">
        <p>
          <% if cookies[:cookies_policy] == "analytics_accepted" %>
            <%= t("cookies-banner.accepted.message") %>
          <% else %>
            <%= t("cookies-banner.rejected.message") %>
          <% end %>
          <%= t(
            "cookies-banner.link.you_can_at_any_time",
            link: link_to(
              t("cookies-banner.link.change_your_cookie_settings"),
              "/cookies/edit")
            ).html_safe
          %>
        </p>
      </div>
    </div>
  </div>
  <div class="govuk-button-group">
    <%= button_to t("cookies-banner.button.hide_this_message"),
        "/cookies/hide_this_message",
        method: :post,
       class: "govuk-button"
    %>
  </div>
</div>

app/views/cookies/_action_required.html.erb
<div class="govuk-cookie-banner__message govuk-width-container">
  <div class="govuk-grid-row grid-body">
    <div class="govuk-grid-column-two-thirds">
      <h2 class="govuk-cookie-banner__heading govuk-heading-m">
        <%= t('cookies-banner.default.heading') %>
      </h2>
      <div class="govuk-cookie-banner__content">
        <p><%= t('cookies-banner.default.message_1') %></p>
        <p><%= t('cookies-banner.default.message_2') %></p>
      </div>
    </div>
  </div>
  <div class="govuk-button-group">
    <%= button_to t('cookies-banner.button.accept_analytics'),
        "/cookies/accept_analytics",
        method: :post,
        class: "govuk-button"
    %>
    <%= button_to t('cookies-banner.button.reject_analytics'),
        "/cookies/reject_analytics",
        method: :post,
        class: "govuk-button"
    %>
    <%= link_to t('cookies-banner.link.view_cookies'),
         Rails.application.routes.url_helpers.cookies_path,
        class: "govuk-link"
    %>
  </div>
</div>

app/views/cookies/_banner.html.erb
<% unless cookies.present? && cookies[:cookies_preferences_set] %>
  <div class="govuk-cookie-banner " data-nosnippet role="region" aria-label="<%= t('cookies-banner.default.heading') %>">
    <% if cookies.present? && cookies[:cookies_policy] %>
      <%= render partial: "cookies/action_confirmed" %>
    <% else %>
      <%= render partial: "cookies/action_required" %>
    <% end %>
  </div>
<% end %>

app/views/cookies/edit.html.erb
<% content_for :title, t(".heading") %>

<%= form_tag "/cookies", method: :patch do %>
  <div class="govuk-grid-row grid-body">
    <div class="govuk-grid-column-two-thirds">
      <% if params[:cookies_updated] %>
        <div class="govuk-notification-banner govuk-notification-banner--success" role="alert" aria-labelledby="govuk-notification-banner-title" data-module="govuk-notification-banner">
          <div class="govuk-notification-banner__header">
            <h2 class="govuk-notification-banner__title" id="govuk-notification-banner-title">
              <%= t('.updated.success') %>
            </h2>
          </div>
          <div class="govuk-notification-banner__content">
            <p class="govuk-notification-banner__heading">
              <%= t('.updated.you_set_your_cookie_preferences') %>
            </p>
          </div>
        </div>
      <% end %>
      <h1 class="govuk-heading-l"><%= t('.heading') %></h1>
      <p class="govuk-body"><%= t('.text_1') %></p>
      <p class="govuk-body"><%= t('.text_2') %></p>
      <h2 class="govuk-heading-m"><%= t('.cookie_settings.subheading') %></h2>
      <p class="govuk-body"><%= t('.cookie_settings.text_1') %></p>
      <div class="govuk-form-group">
      <fieldset class="govuk-fieldset">
        <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
          <h2 class="govuk-heading-m"><%= t('.analytics_cookies.subheading') %></h2>
          <p class="govuk-body"><%= t('.analytics_cookies.text_1') %></p>
          <p class="govuk-body"><%= t('.analytics_cookies.text_2') %></p>
          <ul class="govuk-list govuk-list--bullet">
            <li><%= t('.analytics_cookies.list_item_1') %></li>
            <li><%= t('.analytics_cookies.list_item_2') %></li>
            <li><%= t('.analytics_cookies.list_item_3') %></li>
          </ul>
        </legend>
        <div class="govuk-radios">
          <div class="govuk-radios__item">
            <%= radio_button_tag :analytics, :accept,
                (cookies[:cookies_policy] && cookies[:cookies_policy] == "analytics_accepted"),
                class: "govuk-radios__input" %>
            <%= label_tag :analytics_accept,
                t('.analytics_cookies.radio_button_label.accept'),
                class: "govuk-label govuk-radios__label" %>
          </div>
          <div class="govuk-radios__item">
            <%= radio_button_tag :analytics, :reject,
                !(cookies[:cookies_policy] && cookies[:cookies_policy] == "analytics_accepted"),
                class: "govuk-radios__input" %>
            <%= label_tag :analytics_reject,
                t('.analytics_cookies.radio_button_label.reject'),
                class: "govuk-label govuk-radios__label" %>
          </div>
        </div>
      </fieldset>
    </div>
    <h2 class="govuk-heading-m"><%= t('.essential_cookies.subheading') %></h2>
    <p class="govuk-body"><%= t('.essential_cookies.text_1') %></p>
    <p class="govuk-body"><%= t('.essential_cookies.text_2') %></p>
    <p class="govuk-body"><%= link_to t('.find_out_more.text'), t('.find_out_more.url') %></p>
    <%= submit_tag t('.submit_button'), class: "govuk-button" %>
  </div>
<% end %>

app/views/layouts/pafs.html.erb
<% content_for(:head) do %>
  <!--[if gt IE 8]><!--><%= stylesheet_link_tag "application", media: "all" %><!--<![endif]-->
  <!--[if IE 6]><%= stylesheet_link_tag "application-ie6" %><![endif]-->
  <!--[if IE 7]><%= stylesheet_link_tag "application-ie7" %><![endif]-->
  <!--[if IE 8]><%= stylesheet_link_tag "application-ie8" %><![endif]-->
  <meta name="format-detection" content="telephone=no" />

  <%= render partial: "shared/google_tagmanager" if ENV['GOOGLE_TAGMANAGER_ID'].present? %>
<% end %>

<% content_for :page_title, title %>

<% content_for :cookies_banner do %>
  <%= render partial: "cookies/banner" %>
<% end %>

<% content_for :header_content do %>
  <% content_tag(:span, class: "govuk-header__service-name") { t(:global_proposition_header) } %>
<% end %>

<% content_for :phase_banner do %>
  <div class="govuk-phase-banner">
    <p class="govuk-phase-banner__content">
      <strong class="govuk-tag govuk-phase-banner__content__tag">
        <%= t(".beta")  %>
      </strong>
      <span class="govuk-phase-banner__text">
        <%= t(
              ".feedback",
              link: link_to(
                t(".feedback_link"),
                t(".feedback_url"),
                class: "govuk-link",
                target: "_blank"
              )
            ).html_safe
        %>
      </span>
    </p>
  </div>
  <% if not_policy_page?(request.path) && user_signed_in?%>
    <%= render "shared/user_bar" %>
  <% end %>
  <%= render "shared/return_to_overview" if show_return_to_overview? %>
<% end %>

<% content_for :body_end do %>
  <%= javascript_include_tag "application" %>
<% end %>

<% content_for :footer do %>
  <span class="govuk-visually-hidden"><%= t("global.footer_support_text") %></span>
  <p class="govuk-!-font-weight-bold">
    <%= t("global.footer_support_text") %>
    <%= link_to t("global.helpline_telephone_number"), "tel:#{t("global.helpline_telephone_number").delete(" ") }" %>
  </p>
  <ul class="govuk-footer__inline-list">
    <li class="govuk-footer__inline-list-item">
      <%= link_to "Privacy", main_app.page_path('privacy_notice'), class: "govuk-footer__link" %>
    </li>
    <li class="govuk-footer__inline-list-item">
      <%= link_to "Cookies", Rails.application.routes.url_helpers.cookies_path, class: "govuk-footer__link" %>
    </li>
    <li class="govuk-footer__inline-list-item">
      <%= link_to "Accessibility", "/pages/accessibility", class: "govuk-footer__link" %>
    </li>
  </ul>
<% end %>

<% content_for :footer_support_links do %>
  <div class="ea-footer">
    <p><%= t('global.footer_support_text') %> <%= link_to t("global.helpline_telephone_number"), "tel:#{t("global.helpline_telephone_number").delete(" ") }" %></p>

    <ul class="inline-list">
      <li class="inline"><%= link_to 'Privacy', main_app.page_path('privacy_notice'), target: '_blank' %></li>
      <li class="inline"><%= link_to 'Cookies', Rails.application.routes.url_helpers.cookies_path,  target: '_blank' %></li>
      <li class="inline"><%= link_to 'Accessibility', "/pages/accessibility",  target: '_blank' %></li>
    </li>

    </ul>
  </div>
<% end %>

<%= render template: "layouts/defra_ruby_template" %>

app/views/pages/cookies.html.erb
<% content_for :title, t(".heading") %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l"><%= t('.heading') %></h1>
    <p class="govuk-body"><%= t('.text_1') %></p>
    <p class="govuk-body"><%= t('.text_2') %></p>
    <h2 class="govuk-heading-m"><%= t('.cookie_settings.subheading') %></h2>
    <p class="govuk-body"><%= t('.cookie_settings.text_1') %></p>
    <h2 class="govuk-heading-m"><%= t('.analytics_cookies.subheading') %></h2>
    <p class="govuk-body"><%= t('.analytics_cookies.text_1') %></p>
    <p class="govuk-body"><%= t('.analytics_cookies.text_2') %></p>
    <ul class="govuk-list govuk-list--bullet">
      <li><%= t('.analytics_cookies.list_item_1') %></li>
      <li><%= t('.analytics_cookies.list_item_2') %></li>
      <li><%= t('.analytics_cookies.list_item_3') %></li>
    </ul>
    <table class="govuk-table" aria-label="<%= t('.analytics_cookies.subheading') %>">
      <thead class="govuk-table__head">
        <tr class="govuk-table__row">
          <th scope="col" class="govuk-table__header">
            <%= t('.cookies_we_use.name') %>
          </th>
          <th scope="col" class="govuk-table__header">
            <%= t('.cookies_we_use.purpose') %>
          </th>
          <th scope="col" class="govuk-table__header">
            <%= t('.cookies_we_use.expires') %>
          </th>
        </tr>
      </thead>
      <tbody class="govuk-table__body">
        <% %i{ ga gid }.each do |cookie| %>
          <tr class="govuk-table__row">
            <td class="govuk-table__cell">
              <strong><%= t(".cookies_we_use.#{cookie}.name") %></strong>
            </td>
            <td class="govuk-table__cell">
              <%= t(".cookies_we_use.#{cookie}.purpose") %>
            </td>
            <td class="govuk-table__cell">
              <%= t(".cookies_we_use.#{cookie}.expires") %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <h2 class="govuk-heading-m"><%= t('.essential_cookies.subheading') %></h2>
    <p class="govuk-body"><%= t('.essential_cookies.text_1') %></p>
    <p class="govuk-body"><%= t('.essential_cookies.text_2') %></p>
    <table class="govuk-table">
      <caption class="govuk-visually-hidden">
        <%= t('.cookies_we_use.subheading') %>
      </caption>
      <thead class="govuk-table__head">
        <tr class="govuk-table__row">
          <th scope="col" class="govuk-table__header">
            <%= t('.cookies_we_use.name') %>
          </th>
          <th scope="col" class="govuk-table__header">
            <%= t('.cookies_we_use.purpose') %>
          </th>
          <th scope="col" class="govuk-table__header">
            <%= t('.cookies_we_use.expires') %>
          </th>
        </tr>
      </thead>
      <tbody class="govuk-table__body">
        <% %i[_pafs_session cookies_preferences_set cookies_policy].each do |cookie| %>
          <tr class="govuk-table__row">
            <td class="govuk-table__cell">
              <%= t(".cookies_we_use.#{cookie}.name") %>
            </td>
            <td class="govuk-table__cell">
              <%= t(".cookies_we_use.#{cookie}.purpose") %>
            </td>
            <td class="govuk-table__cell">
              <%= t(".cookies_we_use.#{cookie}.expires") %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <h2 class="govuk-heading-m"><%= t('.change_your_cookie_settings.subheading') %></h2>
    <p class="govuk-body"><%= t('.change_your_cookie_settings.text_1', edit_path: edit_cookies_path).html_safe %></p>
  </div>
</div>

app/views/pages/start.html.erb
<% content_for :title, "Start" %>
<div class="govuk-grid-row grid-body">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l">Submit a proposal for flood and coastal erosion risk management project funding</h1>

    <div class="form-group">
      <p class="list-intro">Use this service to:</p>
      <ul class="list-bullet spaced-list">
        <li>create a proposal for flood and coastal erosion risk management project funding</li>
        <li>return at any time to add more detail to existing proposals</li>
        <li>submit a proposal or resubmit it if you've made changes</li>
      </ul>
    </div>

    <div class="form-group">
      <p>
        <%= link_to t('.start_now'), pafs_core.projects_path, class: "button button-start", role: "button" %>
      </p>
    </div>

    <h2 class="heading-medium">Before you start</h2>
    <p>
      You will need an account to use this service, if you don't have one, you can <%= link_to t('request_an_account_link').downcase, new_account_request_path %>.
    </p>
    <p class="list-intro">
      To submit a proposal you'll need to tell us:
    </p>
    <div class="form-group">
      <ul class="list-bullet spaced-list">
        <li>how you expect to fund the project</li>
        <li>the amount of funding likely to be required</li>
        <li>when the project is likely to spend funds</li>
        <li>the number of households the project is likely to benefit</li>
        <li>any likely environmental benefits</li>
        <li>any other likely financial benefits</li>
      </ul>
    </div>
    <p>
      The <%= link_to t(".partnership_funding_guidance_link"), t(".partnership_funding_guidance_link_target"), rel: "external", target: "_blank" %> and <%= link_to t(".multi_coloured_manual_link"), t(".multi_coloured_manual_link_target"), rel: "external", target: "_blank" %> may help you.
    </p>
  </div>
</div>

app/views/reset_password/reset.html.erb
<% content_for :title, "Reset password confirmation" %>
<div class="step-container">
  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <div class="govuk-box-highlight">
        <h1 class="bold-large">Password reset request</h1>
        <p>We have sent an email to<br/>
        <strong class="heading-medium"><%= flash[:email] %></strong>
        </p>
      </div>
      <h2 class="heading-medium">What happens next</h2>
      <p>You'll receive a password reset email shortly.</p>
      <p>If you don't receive this email within 30 minutes, contact the Environment Agency at
        <%= link_to t("global.support_email"), "mailto:#{t("global.support_email").delete(" ") }" %>
      </p>
      <div class="form-group">
        <%= link_to t("global.return_to_start"), root_path, class: "button", role: "button" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_cookie_message.html.erb
<%= render "govuk_publishing_components/components/cookie_banner", {
  title: "Cookies on Project Application and Funding Service",
  text: sanitize("We use some essential cookies to make this service work.
                  <br><br>
                  We’d also like to use analytics cookies so we can understand how you use the service and make improvements."),
  confirmation_message: sanitize("You’ve accepted all cookies. You can <a class='govuk-link' href='/cookies'>change your cookie settings</a> at any time."),
  services_cookies: {
    yes: {
      text: "Accept analytics cookies",
      data_attributes: {
        "track-category": "cookieBanner"
      }
    },
    no: {
      text: "Reject analytics cookies",
      data_attributes: {
        "track-category": "cookieBanner"
      }
    },
    cookie_preferences: {
      text: "View cookies",
      href: cookies_path
    }
  }
} %>

app/views/shared/_email_support.html.erb
<p>If you have any queries, email us at <%= mail_to t("global.support_email") %></p>

app/views/shared/_email_support.text.erb
If you have any queries, email us at <%= t("global.support_email") %>

app/views/shared/_forgotten_password.html.erb
<details class="govuk-details" data-module="govuk-details">
  <summary>I have forgotten my password</summary>
  <div class="panel">
    <p>If you don't know the password confirmed to you by email when your account was created, you can <%= link_to t("reset_your_password_link"), new_password_path(resource_name) %></p>
  </div>
</details>